version: '3.8'

services:

  django:
    container_name: epic-7-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /start
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1